-- Казахские названия тем. Запускать после 02_topics.sql.
-- Термины стоит глянуть глазами: если что-то звучит не так,
-- как ты говоришь на уроке, поправь прямо в Table Editor.

update topics set title_kk = 'Жай бөлшектер' where code = '1.1';
update topics set title_kk = 'Ондық бөлшектер' where code = '1.2';
update topics set title_kk = 'Амалдар реті және жақшалар' where code = '1.3';
update topics set title_kk = 'Теріс сандар және модуль' where code = '1.4';
update topics set title_kk = 'Өлшем бірліктері' where code = '1.5';
update topics set title_kk = 'Санның бөлігі және бөлігі бойынша сан' where code = '2.1';
update topics set title_kk = 'Қалдықтың бөлігі' where code = '2.2';
update topics set title_kk = 'Пайыздар: тура және кері есеп' where code = '2.3';
update topics set title_kk = 'Пайыздың тізбекті өзгеруі' where code = '2.4';
update topics set title_kk = 'Қатынас және қатынас бойынша бөлу' where code = '2.5';
update topics set title_kk = 'Қоспалар, қорытпалар, концентрация' where code = '2.6';
update topics set title_kk = 'Масштаб' where code = '2.7';
update topics set title_kk = 'Бөлінгіштік белгілері' where code = '3.1';
update topics set title_kk = 'Жай сандар және көбейткіштерге жіктеу' where code = '3.2';
update topics set title_kk = 'Ең үлкен ортақ бөлгіш және ең кіші ортақ еселік' where code = '3.3';
update topics set title_kk = 'Бөлгендегі қалдықтар' where code = '3.4';
update topics set title_kk = 'Соңғы цифр және циклділік' where code = '3.5';
update topics set title_kk = 'Бөлгіштер саны, факториал, нөлдер' where code = '3.6';
update topics set title_kk = 'Санның разрядтық жазылуы' where code = '3.7';
update topics set title_kk = 'Өрнектерді ықшамдау' where code = '4.1';
update topics set title_kk = 'Бөлшекті сызықтық теңдеулер' where code = '4.2';
update topics set title_kk = 'Модульді теңдеулер' where code = '4.3';
update topics set title_kk = 'Сызықтық және қос теңсіздіктер' where code = '4.4';
update topics set title_kk = 'Модульді теңсіздіктер' where code = '4.5';
update topics set title_kk = 'Теңдеулер жүйесі' where code = '4.6';
update topics set title_kk = 'Параметрлі теңдеулер' where code = '4.7';
update topics set title_kk = 'Жаңа амалдар' where code = '4.8';
update topics set title_kk = 'Координаталық түзудегі нүкте' where code = '4а.1';
update topics set title_kk = 'Жазықтық, орта нүкте, симметрия' where code = '4а.2';
update topics set title_kk = 'Сызықтық функция' where code = '4а.3';
update topics set title_kk = 'Деректерді оқу' where code = '4а.4';
update topics set title_kk = 'Координаталық жазықтықтағы аудан' where code = '4а.5';
update topics set title_kk = 'Теңестіру, «тауықтар мен қояндар»' where code = '5.1';
update topics set title_kk = 'Екі шарт, «6 кәмпиттен — 7 артық»' where code = '5.2';
update topics set title_kk = 'Жас мөлшері' where code = '5.3';
update topics set title_kk = 'Қарсы және қуып жету қозғалысы' where code = '5.4';
update topics set title_kk = 'Өзен бойымен қозғалыс' where code = '5.5';
update topics set title_kk = 'Орташа жылдамдық' where code = '5.6';
update topics set title_kk = 'Бірлескен жұмыс' where code = '5.7';
update topics set title_kk = 'Құю есептері' where code = '5.8';
update topics set title_kk = 'Сатып алу және пайда' where code = '5.9';
update topics set title_kk = 'Ұзын денелердің қозғалысы' where code = '5.10';
update topics set title_kk = 'Шеңбер бойымен қозғалыс' where code = '5.11';
update topics set title_kk = 'Түзулер қиылысқандағы бұрыштар' where code = '6.1';
update topics set title_kk = 'Үшбұрыш пен төртбұрыштағы бұрыштар' where code = '6.2';
update topics set title_kk = 'Тіктөртбұрыштың периметрі мен ауданы' where code = '6.3';
update topics set title_kk = 'Фигура бөліктері және аудандар қатынасы' where code = '6.4';
update topics set title_kk = 'Дөңгелек' where code = '6.5';
update topics set title_kk = 'Құрама және боялған фигуралар' where code = '6.6';
update topics set title_kk = 'Торкөз қағаз' where code = '6.7';
update topics set title_kk = 'Фигураларды санау' where code = '6.8';
update topics set title_kk = 'Бүктеу және қию' where code = '6.9';
update topics set title_kk = 'Кубтың жазбасы' where code = '7.1';
update topics set title_kk = 'Қарама-қарсы жақтар және көріністер' where code = '7.2';
update topics set title_kk = 'Текшелерден жасалған фигуралар' where code = '7.3';
update topics set title_kk = 'Бояу және кесу' where code = '7.4';
update topics set title_kk = 'Параллелепипед' where code = '7.5';
update topics set title_kk = 'Көріністер мен проекциялар' where code = '7.6';
update topics set title_kk = 'Сандық тізбектер' where code = '8.1';
update topics set title_kk = 'Фигуралық заңдылықтар' where code = '8.2';
update topics set title_kk = 'Қатарлардың қосындысы' where code = '8.3';
update topics set title_kk = 'Шындық пен өтірік' where code = '8.4';
update topics set title_kk = 'Шарт бойынша реттеу' where code = '8.5';
update topics set title_kk = 'Эйлер шеңберлері' where code = '8.6';
update topics set title_kk = 'Іріктеу комбинаторикасы' where code = '8.7';
update topics set title_kk = 'Дирихле принципі' where code = '8.8';
update topics set title_kk = 'Инварианттар және процестер' where code = '8.9';
update topics set title_kk = 'Өлшеу есептері' where code = '8.10';
update topics set title_kk = 'Арифметикалық орта' where code = '9.1';
update topics set title_kk = 'Өлшенген орта' where code = '9.2';
update topics set title_kk = 'Мода және медиана' where code = '9.3';
update topics set title_kk = 'Диаграммалар мен кестелер' where code = '9.4';
update topics set title_kk = 'Ықтималдық' where code = '9.5';
update topics set title_kk = 'Сандық сипаттама тәсілдері' where code = '10.1';
update topics set title_kk = 'Зейінге арналған қақпандар' where code = '10.2';
update topics set title_kk = 'Жауап нұсқаларымен жұмыс' where code = '10.3';
update topics set title_kk = 'Уақытты басқару' where code = '10.4';
update topics set title_kk = 'Сандық жауапты енгізу' where code = '10.5';

select count(*) filter (where title_kk is null) as без_перевода,
       count(*) as всего from topics;
